apiVersion: batch/v1
kind: CronJob
metadata:
  name: tubescraper
spec:
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: 0 0/12 * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: workload-identity-sa
          containers:
            - name: tubescraper
              image: europe-west4-docker.pkg.dev/pas-shared/pas/tubescraper:latest
              imagePullPolicy: Always
              env:
                - name: STORAGE_BUCKET_NAME
                  value: "pas-prototyping-storage"
                - name: APP_LOG_LEVEL
                  value: "DEBUG"
                - name: API_URL
                  value: "http://core-api:8000/api"
                - name: API_KEYS
                  valueFrom:
                    secretKeyRef:
                      name: core-api-keys
                      key: keys
