type OrgName = str
type Keyword = str
type Topics = dict[Keyword, list[str]]


def preprocess_keywords(
    org_keywords: dict[OrgName, Topics],
) -> dict[str, list[OrgName]]:
    res: dict[str, list[OrgName]] = {}
    for org_name, topic in org_keywords.items():
        for _, keywords in topic.items():
            for keyword in keywords:
                if keyword not in res:
                    res[keyword] = []
                if org_name not in res[keyword]:
                    res[keyword].append(org_name)
    return res


org_keywords: dict[OrgName, Topics] = {
    "Full Fact": {
        "health": [
            "NHS Strikes",
            "Waiting lists",
            "New hospitals",
            "Covid-19 Pandemic",
            "18-week",
            "heart disease",
            "cancer",
            "diabetes",
            "flu",
            "covid",
            "smallpox",
            "mpox",
            "asthma",
            "kidney disease",
            "pancreatitis",
            "embolism",
            "anorexia",
            "bird flu",
            "bronchitis",
            "COPD",
            "measles",
            "hepatitis",
            "hypertension",
            "AIDS",
            "MERS",
            "norovirus",
            "perimenopause",
            "polio",
            "ADHD",
            "migraine",
            "ozempic",
            "SIDS",
            "wart",
        ],
        "climate": [
            "Energy bills",
            "Nuclear plants",
            "Green levies",
            "Gas licences",
            "Wind farms",
            "Net zero",
            "Great British Energy",
            "Energy price cap",
            "Windfall tax",
            "fuel poverty",
        ],
        "EU": [],
        "migration": [
            "Small boat crossings",
            "Small boats",
            "Rwanda policy",
            "Visa applications",
            "Net migration",
            "Illegal migrants",
            "Asylum seekers",
            "Forced returns",
            "asylum hotels",
            "red days",
            "1.2 million illegal migrants",
        ],
        "conflict": [
            "Napoleonic wars",
            "Defence spending",
            "Armed forces",
            "2.5% of GDP",
            "strategic defence review",
            "path to spending 2.5% of GDP on defence",
        ],
    },
    "Maldita": {
        "health": [
            "vacunas",
            "inflamación",
            "grafeno",
            "5G",
            "autismo",
            "cáncer",
            "diabetes",
            "remedios",
            "colesterol",
            "ivermectina",
            "ondas",
            "hormonas",
        ],
        "climate": [
            "sequía",
            "HAARP",
            "geoingeniería",
            "chemtrails",
            "yoduro de plata",
            "cambio climático",
            "fumigaciones",
            "hielo ártico",
            "hielo antártico",
            "glaciación",
            "deshielo",
            "CO2",
            "alarmismo climático",
        ],
        "EU": [
            "fondos europeos",
            "Bruselas",
            "Von de Leyen",
            "OTAN",
            "Parlamento Europeo",
            "Agenda 2030",
            "Ciudad 15 minutos",
            "euro digital",
            "PAC (Política Agraria Común)",
            "Pacto Verde Europeo",
        ],
        "migration": [
            "magrebíes",
            "jovenlandeses",
            "marroquíes",
            "inmigrantes",
            "paguitas",
            "musulmanes",
            "islam",
            "moros",
            "rumanos",
            "senegaleses",
            "argelinos",
            "pateras",
            "cayucos",
            "menas",
            "invasión",
        ],
        "conflict": [
            "drones",
            "misiles",
            "mercenarios",
            "ejecuciones",
            "pallywood",
            "banderitas",
            "ukronazis",
            "bombardeo",
            "guerra mundial",
            "balcanización",
            "masacres",
            "genocidio",
            "otanistas",
        ],
    },
    "APA": {
        "health": [
            "Corona-Chaos",
            "Impfverweigerer",
            "Corona-Lüge",
            "5G",
            "Übersterblichkeit",
            "Turbokrebs",
            "Plötzlich und unerwartet",
            "Impfopfer",
            "Zwangsimpfung",
            "Impfkomplott",
            "Impfnötigung",
            "Genspritze",
            "Pharmalobby",
            "Impfschäden",
        ],
        "climate": [
            "Chemtrails",
            "Klima-Wahn/Klima-Wahnsinn",
            "Klima-Hysterie",
            "Klima-Fanatiker",
            "Klimalüge",
            "Klimaschwindler",
            "Klimalobbyismus",
            "Klima-Terror",
            "Geoengineering",
            "Höllensommer",
            "Konsens-Lüge",
        ],
        "EU": [
            "Brüsseler Diktat",
            "Great Reset",
            "Brüsseler Eurokraten/Brüsseler Eurokratie",
            "Deep State",
            "Überwachungsstaat",
            "Meinungsdiktatur",
            "Gleichschaltung",
            "Ultraliberalismus",
            "Brüsseler Technokraten/Brüsseler Technokratie",
            "Spitzelstaat",
            "Knüppelstaat",
        ],
        "migration": [
            "Asylanten",
            "Remigration",
            "Asyl-Chaos",
            "Messermigrantin",
            "Willkommenskultur",
            "Bahnhofsklatscher",
            "Bevölkerungsaustausch",
            "Migrationsversagen",
            "Asyl-Mafia",
            "Ethnische Säuberung",
            "Asyllobby",
        ],
        "conflict": [
            "Kriegstreiber",
            "Systemmedien",
            "Gender-Wahnsinn",
            "Schlafschafe",
            "Mainstream-Medien",
            "Linksversifft",
            "woke Agenda",
            "Zwangsgebühren",
            "Verlierer-Ampel",
            "Globalisten",
            "Ideologieterror",
            "Moralmission",
        ],
    },
    "LeadStories": {
        "health": [
            "covid",
            "ivermectin",
            "big pharma",
            "pharma shills",
            "shots",
            "injections",
            "fauci",
            "vaccine sceptics",
            "safe and effective",
            "clot shot",
        ],
        "climate": [
            "climate scam",
            "climate alarmism",
            "sea ice",
            "heat island",
            "climate fraud",
            "climate elite",
            "climate sceptics",
            "environmentalism",
            "green jihad",
            "plant food",
        ],
        "EU": [
            "bureaucrats",
            "red tape",
            "undemocratic",
            "overlords",
            "Brussels",
            "EUrabia",
            "Eurocrats",
            "overregulated",
            "elites",
            "EU regulation",
        ],
        "migration": [
            "crimigrants",
            "illegals",
            "flooding across the border",
            "fentanyl",
            "drug traffickers",
            "child traffickers",
            "mexican rapists",
            "border crisis",
            "border emergency",
            "ICE raids",
        ],
        "conflict": [
            "bandera",
            "puppets",
            "NATO expansion",
            "peaceful solution",
            "hostages",
            "warmongers",
            "defense industrial complex",
            "putin shills",
            "Ukrainian nazis",
            "most corrupt country",
        ],
    },
    "Newtral": {
        "health": [
            "Pandemia",
            "Covid",
            "Vacunas",
            "Inyecciones ",
            "Repentinitis ",
            "Cáncer",
            "Enflautamientos",
            "Muerte repentina",
            "Plandemia",
            "Experimentos",
            "Inoculaciones",
            "Vacunas Covid",
            "ARNm",
            "Turbocáncer",
        ],
        "climate": [
            "Cambio climático",
            "Cambio cromático",
            "Agenda 2030",
            "Agenda climática",
            "OTAN",
            "Globalistas",
            "Ecofascistas",
            "Chemtrails",
            "Israel ",
            "Geoingeniería",
            "Fumigaciones masivas",
            "Coches eléctricos",
            "Paneles solares ",
            "Energía renovable",
            "Minería de litio",
        ],
        "EU": [
            "Dictadura Europea",
            "Élites Europeas ",
            "Europa Federal",
            "Control centralizadoSanciones Económicas",
            "Bruselas ",
            "IntervencionismoEurocracia ",
            "Monopolio europeo",
            "Impuesto Europeo",
            "Burócratas europeos ",
            "Burócratas de Bruselas",
        ],
        "migration": [
            "Inmigrantes",
            "Inmigración / Inmigración masiva ",
            "inmigrantes ilegales",
            "remigración jovenlandés",
            'Menores no acompañados" / Menas',
            "Los que no comen jamón Negacionistas del jamón ",
            'El gran reemplazo" ',
            "Multiculturalismo",
            "Invasión",
            "Asilo ",
            "Refugiados",
            "Enriquecedores culturales",
        ],
        "conflict": [
            "Ucrania ",
            "Rusia",
            "PutinZelenski",
            "Ucrania Nazi / UcronaziPalestina",
            "Gaza ",
            "antirruso",
            "Fascismo en Ucrania",
            "Hamás ",
            "Sionismo / Sionista",
            "Netanyahu",
            "Genocidio ",
        ],
    },
    "DPA": {
        "health": [
            "Big Pharma",
            "Impfzwang",
            "Giftstoffe in Impfstoffen",
            "5G",
            "Plandemie",
            "Genmanipulation",
            "WHO-Verschwörung",
            "Chemtrails",
            "Turbokrebs",
            "mRNA-Gentherapie",
        ],
        "climate": [
            "Klimaschwindel",
            "Klimalüge",
            "HAARP",
            "Geoengineering",
            "Klimadiktatur",
            "Klimahysterie",
            "CO2 ist Pflanzennahrung",
            "Wettermanipulation",
            "Cloudseeding",
            "FreieEnergie",
        ],
        "EU": [
            "EU-Diktatur",
            "Freimaurer",
            "Vermögensregister",
            "Eliten",
            "Bevölkerungskontrolle",
            "Souveränitätsverlust",
            "Meinungsdiktatur",
            "NeueWeltordnung",
            "NWO",
            "digitalereuro",
        ],
        "migration": [
            "Migrationsflut",
            "Umvolkung",
            "Islamisierung",
            "Sozialmissbrauch",
            "Bevölkerungsaustausch",
            "Goldstücke",
            "Stolzmonat",
            "Fachkraft",
            "DeutschlandZuerst",
            "Migrantengewalt",
        ],
        "conflict": [
            "Deep State",
            "Globalisten",
            "Kriegstreiber",
            "falseflag",
            "StopptDenKrieg",
            "Krieg ",
            "Wehrpflicht",
            "Gaza",
            "Ukraine",
            "Russland",
        ],
    },
    "Verificat": {
        "health": [
            "descalcificar tu glándula pineal",
            "PLANdemia",
            "Se vacuna y muere",
            "dióxido de cloro",
            "covidiotas",
            "Médicos colaboracionistas",
            "Gafas con filtro amarillo",
            "Contaminación electromagnética",
            "callo solar",
            "óxido de grafeno",
        ],
        "climate": [
            "cambio cromático",
            "nuevo orden mundial",
            "geoingeniería ",
            "Nos fumigan",
            "El clima es cíclico",
            "El clima ha cambiado siempre",
            "cambio timático",
            "alarmismo climático",
            "pedos de vaca",
            "hervimiento global",
        ],
        "EU": [
            "comer insectos",
            "ESCUDO DEMOCRÁTICO EUROPEO",
            "represión de la libertad de expresión",
            "von der puten",
            "séquito globalista 2030",
            "Christine Lagarta",
            "Pústula von der Leyen",
            "Censura Digital",
            "Sociedad vigilada",
            "ChatControl",
        ],
        "migration": [
            "invasión migratoria",
            "gran reemplazo",
            "reemplazo demográfico",
            "islamización",
            "nos invaden",
            "deportaciones masivas",
            "caos migratorio",
            "inmigración masiva",
            "reincidencia",
            "menas",
        ],
        "conflict": [
            "Bioterrorismo",
            "Gobierno nazi de Ucrania",
            "marioneta de la OTAN",
            "propaganda antisemita",
            "relato único",
            "tercera Guerra Mundial",
            "holocausto nuclear",
            "terroristas islámicos",
            "yihadismo",
            "ayuda humanitaria china",
        ],
    },
    "Dogrula": {
        "health": [
            "covid-19",
            "alternatif tedavi",
            "mucize ilaç",
            "doğal",
            "organik",
            "aşı sonrası",
            "mutasyon",
            "laboratuvarda üretilen",
            "kansere neden oluyor",
            "yan etki",
        ],
        "climate": [
            "kıyamet senaryosu",
            "enerji lobisi",
            "küresel ısınma",
            "felaket tellalığı",
            "küresel oyun",
            "yeni dünya düzeni",
            "elektrikli araçlar",
            "enerji arzı",
            "en sıcak gün",
            "küreselciler",
        ],
        "EU": [
            "egemenlik kaybı",
            "kültürel erozyon",
            "gizli anlaşma",
            "dış güçler",
            "borçlandırma politikası",
            "kültürel asimilasyon",
            "dış müdehale",
            "batının oyunu",
            "diplomatik baskı",
            "lgbt dayatması",
            "ekonomik vesayet",
        ],
        "migration": [
            "sınır güvenliği",
            "kontrolsüz giriş",
            "iç savaş",
            "güvenlik zafiyeti",
            "silah kaçakçılığı",
            "sığınmacılar",
            "ekonomik yük",
            "suriyeliler",
            "ucuz işçi",
            "vatandaşlık verilmesi",
            "milli güvenlik",
            "araplaşma",
            "oy almak için",
        ],
        "conflict": [
            "israil",
            "filistin",
            "suriye",
            "gazze",
            "yardım peketi",
            "netanyahu",
            "yahudi lobisi",
            "siyonizm",
            "toprak sattılar",
            "insani yardım",
        ],
    },
    "Info-veritas": {
        "health": [
            "Síntomas",
            "Tratamiento",
            "Dolor",
            "Cáncer",
            "Depresión",
            "Diabetes",
            "Ansiedad",
            "Vacunas ",
            "Médico",
            "Diabetes",
            "Salud Mental",
            "Psicólogo",
            "Ozempic",
        ],
        "climate": [
            "Calor",
            "Alerta por calor",
            "Fenómenos meteorológicos",
            "AEMET",
            "DANA",
            "Tiempo hoy",
            "Calentamiento global",
            "huracanes",
            "tormenats tropicales",
        ],
        "EU": [
            "Parlamento Europeo",
            "Comisión Europea",
            "Euro",
            "Seguridad",
            "Aranceles",
            "Seguridad",
            "países",
            "fronteras",
            "kit supervivencia",
            "Ursula von der Leyen",
            "objetivos",
            "valores",
        ],
        "migration": [
            "Regulación",
            "asilo",
            "refugiados",
            "fronteras",
            "crisis migratoria",
            "menor extranjero no acompañado (MENA)",
            "retornos",
            "centros de deportación",
        ],
        "conflict": [
            "Ucrania-Rusia/Israel-Gaza",
            "genocidio",
            "seguridad",
            "paz",
            "acuerdo/ acuerdo de paz",
            "alto el fuego",
            "conflictos armados actuales",
            "crisis",
        ],
    },
    "PA Media": {
        "health": [
            "vaccine",
            "autism",
            "poison",
            "detox",
            "natural",
            "distracted",
            "nurses",
            "waiting list",
            "NHS",
            "mRNA",
        ],
        "climate": [
            "dunkelflaute",
            "intermittant",
            "net zero",
            "hoax",
            "main stream",
            "privatised",
            "birds",
            "freeze energy",
            "China coal",
            "winter fuel",
        ],
        "EU": [],
        "migration": [
            "hotels",
            "small boats",
            "dinghy ",
            "English Channel",
            "repatriate",
            "usual suspects",
            "import people",
            "values",
            "communities",
            "rape gang",
            "racist",
        ],
        "conflict": [],
    },
}
