from collections.abc import Iterable

type ChannelName = str
type OrgName = str
type ChannelPair = tuple[ChannelName, OrgName]
type ChannelWatchers = dict[ChannelName, list[OrgName]]


def preprocess_channels(channels: Iterable[ChannelPair]) -> ChannelWatchers:
    """FIXME: turns the tuples to a dict bc we have duplicates..."""

    res: dict[str, list[str]] = {}
    for channel, org in channels:
        if res.get(channel):
            res[channel].append(org)
        res[channel] = [org]
    return res


channels: list[ChannelPair] = [
    ("@auf1tv", "APA"),
    ("@martinrutter", "APA"),
    ("@0punkt", "APA"),
    ("@BrandonLehman", "LeadStories"),
    ("@Freedom-Frontline", "LeadStories"),
    ("@FameRushTV", "LeadStories"),
    ("@LovelyTrumpFamily", "LeadStories"),
    ("@EliteVehicles", "LeadStories"),
    ("@TheEconomicTimes", "LeadStories"),
    ("@StorytimeWithGreen", "LeadStories"),
    ("@Okayrick", "LeadStories"),
    ("@FactsVerse", "LeadStories"),
    ("@SurprisingStories21", "LeadStories"),
    ("@UncensoredInsighte", "LeadStories"),
    ("@kevin_24x7", "LeadStories"),
    ("@BodycamDeclassified-x5k", "LeadStories"),
    ("@HollywoodNewsAndGossip", "LeadStories"),
    ("@CELEBLIVETV-t9r", "LeadStories"),
    ("@HotTea-YT", "LeadStories"),
    ("@ViOneMedia", "Newtral"),
    ("@NegociosTV", "Newtral"),
    ("@javiercardenasofficial", "Newtral"),
    ("@Capitan_Bitcoin", "Newtral"),
    ("@WallStreetWolverine", "Newtral"),
    ("@distritotv0", "Newtral"),
    ("@DesokupaTV", "Newtral"),
    ("@MiguelRuizCalvo", "Newtral"),
    ("@ChechuLeduc", "Newtral"),
    ("@multicanalr", "Newtral"),
    ("@RubenGisbert", "Newtral"),
    ("@Aniquilandolahistoria", "Newtral"),
    ("@EstadodeAlarmaTV", "Newtral"),
    ("@DanielLacalleOfficial", "Newtral"),
    ("@geoestratego_oficial", "Newtral"),
    ("@INQUIETAMENTEesp", "Newtral"),
    ("@castillonconfidencial8338", "Newtral"),
    ("@AGUAIURIS", "Newtral"),
    ("@Vermietertagebuch", "dpa"),
    ("@Kapit", "dpa"),
    ("@KettnerEdelmetalle", "dpa"),
    ("@PolitikmitKopf", "dpa"),
    ("@GunterSpeckacht", "dpa"),
    ("@Politik", "dpa"),
    ("@EuroplanetariumTV", "dpa"),
    ("@hkcm", "dpa"),
    ("@kontraste", "dpa"),
    ("@BITCOIN-HOTEL", "dpa"),
    ("@AchtungReichelt", "dpa"),
    ("@rtvooe", "dpa"),
    ("@auf1tv", "dpa"),
    ("@KlaTv", "dpa"),
    ("@Actuarium", "dpa"),
    ("@elxokasshorts", "Verificat"),
    ("@UnTioBlancoHetero", "Verificat"),
    ("c/VoxEspa%C3%B1aTV", "Verificat"),
    ("@Dietalvaro", "Verificat"),
    ("@DalasReview", "Verificat"),
    ("@TuAbogadoParticular", "Verificat"),
    ("@vemarket", "Verificat"),
    ("@Televisionconsciente", "Verificat"),
    ("@javiercardenasofficial", "Verificat"),
    ("@DavidSantosVlog", "Verificat"),
    ("c/Cl%C3%ADnicaMedicinaIntegrativa", "Verificat"),
    ("@Tecnonauta", "Verificat"),
    ("@RubenGisbert", "Verificat"),
    ("@FRANPAREJO", "Verificat"),
    ("@worldcast_", "Verificat"),
    ("@ConflictTR-", "Dogrula"),
    ("@CzrHaber", "Dogrula"),
    ("@misvakcaps", "Dogrula"),
    ("@yirmiucderece", "Dogrula"),
    ("@KanalTurkiyeYoutube", "Dogrula"),
    ("@tarihbuyuk", "Dogrula"),
    ("@trhaber_com", "Dogrula"),
    ("@AkitKanal", "Dogrula"),
    ("@TurkiyePolitics", "Dogrula"),
    ("@REYHANISAADET", "Dogrula"),
    ("@yenisabah", "Dogrula"),
    ("@ibrahimHaskologlu", "Dogrula"),
    ("@sirlaralemitv", "Dogrula"),
    ("@TurhanBozkurt", "Dogrula"),
    ("@ww3medya", "Dogrula"),
    ("@herqlestv", "Info-veritas"),
    ("@geoestratego_oficial", "Info-veritas"),
    ("@EstadodeAlarmaTV", "Info-veritas"),
    ("@Un_Abogado_Contra_la_Demagogia", "Info-veritas"),
    ("@PoliticaenPrimeraLinea", "Info-veritas"),
    ("@ESPAÑAaldia28", "Info-veritas"),
    ("@Lorenasanztrincheralibre", "Info-veritas"),
    ("c/MEDITERRÁNEODIGITAL", "Info-veritas"),
    ("@ElToro_TV", "Info-veritas"),
    ("@periodistadigital", "Info-veritas"),
    ("@robertovaquero_", "Info-veritas"),
    ("@elpuntoblancoyoutube", "Info-veritas"),
    ("@distritotv0", "Info-veritas"),
    ("@Capitan_Bitcoin", "Info-veritas"),
    ("@antoniogutierrezz", "Info-veritas"),
    ("@DetrásdelDiscurso", "Info-veritas"),
    ("@AgendaEspañaYT", "Info-veritas"),
    ("@grahameardley1851", "PA-Media"),
    ("channel/UCusXYsRQI271wblOw-d3itghannel", "PA-Media"),
    ("@occupiedGaza", "PA-Media"),
    ("@primeroyalmonarchy", "PA-Media"),
    ("@official_usmanm", "PA-Media"),
    ("@blckbx", "Kuleuven.be"),
    ("@LeefBewustNU", "Kuleuven.be"),
    ("@CafeWeltschmerz", "Kuleuven.be"),
    ("@KiesDries", "Kuleuven.be"),
    ("@DwarsNieuws", "Kuleuven.be"),
    ("@OngehoordNederlandTV", "Kuleuven.be"),
    ("@StevenSpreekt", "Kuleuven.be"),
    ("@ForumDemocratie", "Kuleuven.be"),
    ("@nieuwrechtsnl", "Kuleuven.be"),
    ("@JornLuka", "Kuleuven.be"),
    ("@DeNieuweWereldTV", "Kuleuven.be"),
    ("@DeAndereKrant", "Kuleuven.be"),
    ("@EvavanZeeland", "Kuleuven.be"),
    ("@KUKURU", "Kuleuven.be"),
    ("@HeteHangijzers", "Kuleuven.be"),
    ("@Dr_Spitzbart", "donau-uni.ac.at"),
    ("@vitamindking", "donau-uni.ac.at"),
    ("@Gesundheit_Total", "donau-uni.ac.at"),
    ("@ExiledMedicDe", "donau-uni.ac.at"),
    ("@robertfranznaturprodukte7714", "donau-uni.ac.at"),
    ("@Soeren-Schumann", "donau-uni.ac.at"),
    ("@Dr.PetraBracht", "donau-uni.ac.at"),
    ("@glowupgamze", "donau-uni.ac.at"),
    ("@selbergesundwerden", "donau-uni.ac.at"),
    ("@WeltderGesundheit", "donau-uni.ac.at"),
    ("@Aspoonaday", "donau-uni.ac.at"),
    ("@Longevitypraxis", "donau-uni.ac.at"),
    ("@gesunderkollege", "donau-uni.ac.at"),
    ("@Bio360", "donau-uni.ac.at"),
    ("@vitalstoff-medizin", "donau-uni.ac.at"),
]
