services:
  base_image:
    build:
      context: .
      dockerfile: Containerfile
    image: europe-west4-docker.pkg.dev/pas-shared/pas/base_image:latest

  tubescraper:
    build:
      context: ./projects/src/tubescraper
      dockerfile: Containerfile
      additional_contexts:
        base_image: "service:base_image"
    image: europe-west4-docker.pkg.dev/pas-shared/pas/tubescraper:latest

  tubescraper_dev:
    build:
      context: ./projects/src/tubescraper
      dockerfile: Containerfile
      additional_contexts:
        base_image: "service:base_image"
    image: europe-west4-docker.pkg.dev/pas-shared/pas/tubescraper:dev

  tokscraper:
    build:
      context: ./projects/src/tokscraper
      dockerfile: Containerfile
      additional_contexts:
        base_image: "service:base_image"
    image: europe-west4-docker.pkg.dev/pas-shared/pas/tokscraper:latest

  tokscraper_dev:
    build:
      context: ./projects/src/tokscraper
      dockerfile: Containerfile
      additional_contexts:
        base_image: "service:base_image"
    image: europe-west4-docker.pkg.dev/pas-shared/pas/tokscraper:dev
